### ISSUE TITLE
Use pip caches directly instead of pip-accel

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-docker#11]
Still have to investigate how to do it, but it seems possible to use pip to generate the caches and just ship that instead of populating them with pip-accel (that does not work with latest pip).

This is the main docs page: https://pip.pypa.io/en/stable/reference/pip_install/#wheel-cache

**Comment by david-caro** [comment]
Pip accell actually uses pip underneath, so it's not really an advantage. And it's already adapting to pip 8 (pip changed the way it caches the deps and how to generate that dir...) so I don't think it's worth the effort right now, we can just wait for the next pip-accel release to get pip8 support. The pip8 issue: paylogic/pip-accel#73

@mihaibivol any ideas/comments?

**Comment by mihaibivol** [comment]
As long as we are kind of sure that `pip install == pip-accel install` (but with better caching, then we can keep using pip-accel)

**Comment by david-caro** [comment]
according to their docs it's not the same, as it seems that pip does not support installing packages from binary distributions (sounds strange): https://github.com/paylogic/pip-accel#control-flow-of-pip-accel

It uses pip for the download of the sources when needed, but for the install itself it installs 'manually'

**Comment by david-caro** [comment]
Found a way to do something similar with pip:
```
pip wheel --wheel-dir=somewhere -r deps.txt  # downloads and builds
pip install --find-links=somewhere -r deps.txt
```
The first one populates the source cache, and creates a 'binary cache', the second picks up from both (the source cache is at ~/.cache/pip, but it can be changed)

**Comment by david-caro** [comment]
that change requires modification in this repo, and on the inspire-next compose files... is there any process to do that 'swiftly'?

**Comment by david-caro** [comment]
@kaplun ^ maybe you know?

**Comment by david-caro** [comment]
Actually, the only issue that might happen is that the tests run a bit slower (as it would have to download all the packages)

**Comment by jacquerie** [comment]
> that change requires modification in this repo, and on the inspire-next compose files... is there any process to do that 'swiftly'?

AFAIK, not with our current repo structure. We can just do it after everybody leaves for the weekend, and it would be invisible to most.
