### ISSUE TITLE
Retry the commands that are most likely to fail on travis

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-docker#13]
Check which commands are more likely to fail (usually the ones that depend on external services, specially building the images as it pulls stuff from a bunch of different repositories) and retry them on failure so it's less like to break the build

**Comment by mihaibivol** [comment]
I think this one has precedence over all others since the build is kind of flaky now. Do you think that we need to get more granular than retrying only `build.sh` and `deploy.sh`

**Comment by david-caro** [comment]
For those sections no, but for the test.sh as it takes quite a lot of time to run whole, I'm right now working on figuring out what's the best strategy there on a branch in my fork
